// Package sandboxapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package sandboxapi

import (
	"encoding/json"
	"errors"
	"time"

	"github.com/oapi-codegen/runtime"
)

// Defines values for ImageInfoStatus.
const (
	Completed ImageInfoStatus = "completed"
	Failed    ImageInfoStatus = "failed"
	Preparing ImageInfoStatus = "preparing"
)

// Defines values for LogLevelRequestLevel.
const (
	Debug LogLevelRequestLevel = "debug"
	Error LogLevelRequestLevel = "error"
	Info  LogLevelRequestLevel = "info"
	Warn  LogLevelRequestLevel = "warn"
)

// Defines values for NetworkPolicyDebugScope.
const (
	Global  NetworkPolicyDebugScope = "global"
	Sandbox NetworkPolicyDebugScope = "sandbox"
)

// Defines values for PolicyRuleDecision.
const (
	PolicyRuleDecisionAllow PolicyRuleDecision = "allow"
	PolicyRuleDecisionDeny  PolicyRuleDecision = "deny"
)

// Defines values for PolicyRuleOrigin.
const (
	Local  PolicyRuleOrigin = "local"
	Remote PolicyRuleOrigin = "remote"
	Scoped PolicyRuleOrigin = "scoped"
)

// Defines values for PolicyRuleStatus.
const (
	Active   PolicyRuleStatus = "active"
	Inactive PolicyRuleStatus = "inactive"
)

// Defines values for PolicyRuleActionAllowAction.
const (
	PolicyRuleActionAllowActionAllow PolicyRuleActionAllowAction = "allow"
)

// Defines values for PolicyRuleActionDenyAction.
const (
	PolicyRuleActionDenyActionDeny PolicyRuleActionDenyAction = "deny"
)

// Defines values for PolicyRuleActionRemoveIDAction.
const (
	RemoveId PolicyRuleActionRemoveIDAction = "remove-id"
)

// Defines values for PolicyRuleActionRemoveResourceAction.
const (
	RemoveResource PolicyRuleActionRemoveResourceAction = "remove-resource"
)

// Defines values for PolicyRuleResultAction.
const (
	PolicyRuleResultActionAllow          PolicyRuleResultAction = "allow"
	PolicyRuleResultActionDeny           PolicyRuleResultAction = "deny"
	PolicyRuleResultActionRemoveId       PolicyRuleResultAction = "remove-id"
	PolicyRuleResultActionRemoveResource PolicyRuleResultAction = "remove-resource"
)

// Defines values for PolicyRulesListResponseLastSyncedStatus.
const (
	SyncOk   PolicyRulesListResponseLastSyncedStatus = "sync-ok"
	SyncWarn PolicyRulesListResponseLastSyncedStatus = "sync-warn"
)

// Defines values for PolicySetupRequestPreset.
const (
	PolicySetupRequestPresetAllowAll PolicySetupRequestPreset = "allow-all"
	PolicySetupRequestPresetBalanced PolicySetupRequestPreset = "balanced"
	PolicySetupRequestPresetDenyAll  PolicySetupRequestPreset = "deny-all"
)

// Defines values for PolicySetupResponseExistingPreset.
const (
	PolicySetupResponseExistingPresetAllowAll PolicySetupResponseExistingPreset = "allow-all"
	PolicySetupResponseExistingPresetBalanced PolicySetupResponseExistingPreset = "balanced"
	PolicySetupResponseExistingPresetDenyAll  PolicySetupResponseExistingPreset = "deny-all"
)

// Defines values for PortKeyProtocol.
const (
	PortKeyProtocolTcp  PortKeyProtocol = "tcp"
	PortKeyProtocolTcp4 PortKeyProtocol = "tcp4"
	PortKeyProtocolTcp6 PortKeyProtocol = "tcp6"
	PortKeyProtocolUdp  PortKeyProtocol = "udp"
	PortKeyProtocolUdp4 PortKeyProtocol = "udp4"
	PortKeyProtocolUdp6 PortKeyProtocol = "udp6"
)

// Defines values for PortPublishRequestProtocol.
const (
	PortPublishRequestProtocolTcp  PortPublishRequestProtocol = "tcp"
	PortPublishRequestProtocolTcp4 PortPublishRequestProtocol = "tcp4"
	PortPublishRequestProtocolTcp6 PortPublishRequestProtocol = "tcp6"
	PortPublishRequestProtocolUdp  PortPublishRequestProtocol = "udp"
	PortPublishRequestProtocolUdp4 PortPublishRequestProtocol = "udp4"
	PortPublishRequestProtocolUdp6 PortPublishRequestProtocol = "udp6"
)

// Defines values for PublishedPortProtocol.
const (
	Tcp  PublishedPortProtocol = "tcp"
	Tcp4 PublishedPortProtocol = "tcp4"
	Tcp6 PublishedPortProtocol = "tcp6"
	Udp  PublishedPortProtocol = "udp"
	Udp4 PublishedPortProtocol = "udp4"
	Udp6 PublishedPortProtocol = "udp6"
)

// Defines values for SandboxCreateRequestPullPolicy.
const (
	Always  SandboxCreateRequestPullPolicy = "always"
	Missing SandboxCreateRequestPullPolicy = "missing"
	Never   SandboxCreateRequestPullPolicy = "never"
)

// Defines values for SandboxCreateResponseStatus.
const (
	SandboxCreateResponseStatusRunning SandboxCreateResponseStatus = "running"
	SandboxCreateResponseStatusStopped SandboxCreateResponseStatus = "stopped"
)

// Defines values for SandboxDebugAuthMode.
const (
	ApiKey SandboxDebugAuthMode = "api_key"
	None   SandboxDebugAuthMode = "none"
	Oauth  SandboxDebugAuthMode = "oauth"
)

// Defines values for SandboxInfoStatus.
const (
	SandboxInfoStatusRunning SandboxInfoStatus = "running"
	SandboxInfoStatusStopped SandboxInfoStatus = "stopped"
)

// Defines values for VersionCheckResponseResult.
const (
	Compatible   VersionCheckResponseResult = "compatible"
	Development  VersionCheckResponseResult = "development"
	Incompatible VersionCheckResponseResult = "incompatible"
)

// AddKitRequest defines model for AddKitRequest.
type AddKitRequest struct {
	// KitArtifact Parsed kit content shipped inline by the client. Mirrors
	// the `kit_artifacts` shape on `SandboxCreateRequest` — the
	// JSON-marshalled form of a `sandboxlib/kit.Artifact` (which
	// embeds `spec.Artifact` from `docker/sbx-kits-contrib`). The
	// client resolves the `--kit` reference locally (OCI, git,
	// ZIP, or path) and ships the parsed artifact here; the
	// daemon `json.Unmarshal`s it back into `kit.Artifact` and
	// applies it to the running container.
	//
	// Same rationale as create-time `kit_artifacts`: the daemon
	// doesn't carry registry / git credentials and shouldn't
	// stat host filesystem paths outside its state directory,
	// so reference resolution stays client-side.
	//
	// Agent-type kits (`kind: sandbox`) are rejected with 400 —
	// runtime injection cannot replace the agent, change
	// security settings, or alter container mounts. Those
	// require sandbox recreation (see the `kit_artifacts` field
	// on `SandboxCreateRequest`).
	KitArtifact map[string]interface{} `json:"kit_artifact"`
}

// CreatedRule defines model for CreatedRule.
type CreatedRule struct {
	Resource string `json:"resource"`
	RuleId   string `json:"rule_id"`
}

// CredentialValue defines model for CredentialValue.
type CredentialValue struct {
	// Service Service name (e.g. "anthropic", "openai")
	Service string `json:"service"`

	// Value Credential value (API key, token)
	Value string `json:"value"`
}

// CustomSecretDebugEntry A custom placeholder->secret mapping, classification-only.
type CustomSecretDebugEntry struct {
	// Class Value classification — populated, empty, or whitespace.
	Class   string `json:"class"`
	EnvName string `json:"env_name"`

	// Sentinel Placeholder key (not secret material).
	Sentinel string `json:"sentinel"`

	// Targets Host patterns for this secret (injection keys, not secret material).
	Targets []string `json:"targets"`

	// Value Always the censored placeholder "***".
	Value string `json:"value"`
}

// CustomSecretValue defines model for CustomSecretValue.
type CustomSecretValue struct {
	// EnvName Name of the environment variable the sandbox sees.
	EnvName string `json:"env_name"`

	// Sentinel Daemon-side identifier the proxy looks for in request bodies
	// and headers; replaced with the corresponding `value` before
	// the request leaves the host. Non-empty and unique per
	// request body.
	Sentinel string `json:"sentinel"`

	// Target Deprecated — use `targets` instead. Retained for backward
	// compatibility with older clients. The proxy treats a non-empty
	// `target` as equivalent to `targets: [target]` when `targets`
	// is absent.
	Target *string `json:"target,omitempty"`

	// Targets Host patterns the proxy matches against outgoing requests before
	// performing the sentinel-to-value replacement. Multiple entries
	// allow one secret to cover unrelated domains that share the same
	// key. An empty array means the secret matches every host.
	// Supersedes `target` when non-empty.
	Targets *[]string `json:"targets,omitempty"`

	// Value Real secret value the proxy substitutes for the sentinel.
	// Never visible to the sandboxed process — only the proxy and
	// the daemon's secrets store hold it.
	Value string `json:"value"`
}

// DaemonDiagnostics defines model for DaemonDiagnostics.
type DaemonDiagnostics struct {
	// Info Diagnostic snapshot returned by docker-next
	// libdocker.Server.Diagnostics (pkg/diag.Info). The embedder's
	// redactor has already been applied. Modeled as `additionalProperties: true` here so this schema does not need to track docker-next's struct evolution.
	//
	// Canonical schema lives in docker-next:
	//   - RFC: https://github.com/docker/docker-next/blob/main/rfc/013-diagnostics-api.md
	//   - Go type: https://github.com/docker/docker-next/blob/main/pkg/diag/diag.go (type `Info`)
	//
	// Top-level keys (RFC 013, schema_version=1):
	//   - SchemaVersion (int) — bumped on breaking changes.
	//   - CapturedAt (RFC 3339 timestamp, UTC) — when the snapshot was taken.
	//   - Version (object) — build identity: GitSHA, BuildDate, Semver. Empty in unstamped dev builds.
	//   - GoRuntime (string) — e.g. `go1.24.1`.
	//   - NerdboxID (string) — containerd runtime ID, e.g. `io.containerd.nerdbox.v1`.
	//   - Host (object) — OS, Arch, NumCPU, OSVersion (redacted), Memory{TotalBytes, AvailableBytes}.
	//   - Process (object) — Self{PID, RSSBytes}, Shims{Count, TotalRSSBytes}, NumGoroutine, UptimeSec.
	//   - State (object) — Sandboxes{Total, Running, TotalCPUsAllocated, TotalMemoryMiBAllocated}, Images{Count, TotalBytes}. Aggregate counts only — zero PII.
	//   - ContainerdConfig (object) — Version, Root (redacted), State (redacted), DisabledPlugins, RequiredPlugins, Plugins (every string value recursively redacted), Timeouts (keys + values redacted).
	//   - Goroutines (array of strings) — one entry per goroutine from runtime.Stack(all=true), redacted. Splitting per-goroutine (rather than emitting a single newline-joined string) keeps the bundle's runtime-diag.json readable when a support reader opens it in jq. Build paths in file:line frames stripped via -trimpath.
	//
	// Consumers that need typed access should unmarshal the JSON into docker-next's `diag.Info` Go type directly — JSON tags match the field names listed above.
	Info map[string]interface{} `json:"info"`

	// PartialError Aggregated non-fatal sub-collector error messages, joined by
	// newline (`\n`). Omitted when the snapshot is complete.
	// Callers should still serialize info regardless of this field —
	// a partial snapshot is more useful than no snapshot.
	PartialError *string        `json:"partial_error,omitempty"`
	SocketPaths  SocketPathInfo `json:"socket_paths"`
}

// DaemonInfo defines model for DaemonInfo.
type DaemonInfo struct {
	// ApiSocket Path to the sandboxd API socket
	ApiSocket string `json:"api_socket"`

	// DockerSocket Path to the docker backend socket (shared by all sandboxes).
	// DEPRECATED: clients should not depend on direct access to this
	// socket; it may be made internal to sandboxd in a future release.
	// Use the sandboxd API endpoints instead
	// (e.g. /sandbox/{name}/exec, /sandbox/{name}/files).
	// Deprecated:
	DockerSocket *string `json:"docker_socket,omitempty"`
}

// DebugStateResponse Read-only debug snapshot of daemon internal state. Never contains secret values.
type DebugStateResponse struct {
	// DaemonUptimeSeconds Seconds since the daemon process started (best-effort).
	DaemonUptimeSeconds float64 `json:"daemon_uptime_seconds"`

	// DaemonVersion Daemon build version string.
	DaemonVersion string `json:"daemon_version"`

	// Docker Scan of all containers and networks on the Docker daemon.
	Docker DockerScanDebug `json:"docker"`

	// Drift Cross-reference of in-memory runtimes against Docker daemon state.
	Drift DriftReport `json:"drift"`

	// Sandboxes Per-sandbox runtime state, including the secrets injected into each.
	Sandboxes []SandboxDebug `json:"sandboxes"`

	// StoredSecrets Read-only view of what is persisted in the host credential store (keychain or encrypted file). Presence/identity only — never contains secret values.
	StoredSecrets StoredSecretsDebug `json:"stored_secrets"`
}

// DockerContainerDebug defines model for DockerContainerDebug.
type DockerContainerDebug struct {
	Name string `json:"name"`

	// Tracked Whether sandboxd has a runtime tracking this container.
	Tracked bool `json:"tracked"`
}

// DockerNetworkDebug defines model for DockerNetworkDebug.
type DockerNetworkDebug struct {
	Driver string `json:"driver"`
	Name   string `json:"name"`

	// SandboxManaged Whether this is a sandbox-managed (gvisor-driver) network.
	SandboxManaged bool `json:"sandbox_managed"`
}

// DockerScanDebug Scan of all containers and networks on the Docker daemon.
type DockerScanDebug struct {
	Containers []DockerContainerDebug `json:"containers"`
	Networks   []DockerNetworkDebug   `json:"networks"`
}

// DriftReport Cross-reference of in-memory runtimes against Docker daemon state.
type DriftReport struct {
	// ContainersNotTracked Containers not tracked by any sandboxd runtime.
	ContainersNotTracked []string `json:"containers_not_tracked"`

	// NetworksWithoutRuntime gvisor networks with no corresponding tracked runtime (orphans).
	NetworksWithoutRuntime []string `json:"networks_without_runtime"`

	// RuntimesWithoutNetwork Tracked runtimes with no matching gvisor network.
	RuntimesWithoutNetwork []string `json:"runtimes_without_network"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Code Stable machine-readable error code (e.g. "sandbox_not_found",
	// "image_pull_failed"). Optional today; reserved so clients can
	// switch on a typed identifier rather than parsing message text
	// or matching HTTP status codes once we start populating it.
	Code *string `json:"code,omitempty"`

	// Message Human-readable error message.
	Message string `json:"message"`

	// PortReplayConflict Details for a `port_replay_conflict` error returned by
	// `POST /sandbox/{name}/start`. Sandboxes remember published-port
	// requests so they can be restored after the sandbox stops or the
	// daemon restarts. When a remembered request used an explicit host
	// port and that port is already in use during start, sandboxd leaves
	// the sandbox stopped and returns this payload so clients can offer
	// to replace the saved desired mapping with a different host port
	// before retrying `startSandbox`.
	PortReplayConflict *PortReplayConflict `json:"port_replay_conflict,omitempty"`
}

// ExecInspect State of an interactive exec. Returned by
// GET /sandbox/{name}/exec/{exec_id} — callers poll this after
// the upgraded stream from POST /sandbox/{name}/exec/attach
// closes to recover the exit code, mirroring Moby's
// ContainerExecInspect.
type ExecInspect struct {
	// ExitCode Exit code; only meaningful when `running` is false.
	ExitCode int `json:"exit_code"`

	// Id Docker-backend exec ID.
	Id string `json:"id"`

	// Pid PID inside the container; 0 when no longer running.
	Pid *int `json:"pid,omitempty"`

	// Running True while the exec is still running.
	Running bool `json:"running"`
}

// ExecRequest Used as the JSON body of POST /sandbox/{name}/exec (non-
// interactive) and POST /sandbox/{name}/exec/attach (interactive
// — daemon upgrades the connection to a raw bidirectional
// stream). Fields that only apply to interactive sessions
// (e.g. tty) are ignored on the non-interactive endpoint.
type ExecRequest struct {
	// Cmd Command and arguments to execute. Must contain at least one
	// element (the program to run); each element must be non-empty.
	Cmd []string `json:"cmd"`

	// Env Additional environment variables to set inside the exec, as a
	// map of name → value. Same shape as
	// SandboxCreateRequest.environment so clients have one rule for
	// "env vars" across the API.
	Env *map[string]string `json:"env,omitempty"`

	// Tty Allocate a pseudo-TTY. Only meaningful for interactive
	// sessions (POST /sandbox/{name}/exec/attach); ignored by the
	// non-interactive POST /sandbox/{name}/exec endpoint.
	Tty *bool `json:"tty,omitempty"`

	// User User to run as (name or UID, e.g. "root" or "0")
	User *string `json:"user,omitempty"`

	// WorkingDir Working directory inside the container
	WorkingDir *string `json:"working_dir,omitempty"`
}

// ExecResult Result of a non-interactive exec. Named `ExecResult` rather than
// `ExecResponse` so the schema doesn't collide with the generated
// client's `ExecResponse` wrapper type for the `exec` operation.
// (Other operations don't have this collision because their operationId
// doesn't match a noun in the schema namespace.)
type ExecResult struct {
	ExitCode int     `json:"exit_code"`
	Stderr   *string `json:"stderr,omitempty"`
	Stdout   *string `json:"stdout,omitempty"`
}

// ExistingResource defines model for ExistingResource.
type ExistingResource struct {
	Resource string  `json:"resource"`
	RuleId   string  `json:"rule_id"`
	RuleName *string `json:"rule_name,omitempty"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	// ApiVersion Semver API version matching the OpenAPI spec version (see
	// `info.version` for the current value). Absent on old daemons.
	// Clients should compare major versions for compatibility:
	// same major = compatible, different major = incompatible.
	ApiVersion *string `json:"api_version,omitempty"`
	Release    bool    `json:"release"`

	// Revision Daemon build git revision
	Revision *string `json:"revision,omitempty"`

	// Runtime Versions of the daemon's runtime components. Each component
	// carries a `_version` and `_commit` so callers don't have to
	// special-case the shape — fields are optional because not every
	// runtime exposes both.
	Runtime *RuntimeVersions `json:"runtime,omitempty"`
	Status  string           `json:"status"`

	// Version Daemon build version
	Version string `json:"version"`
}

// ImageInfo defines model for ImageInfo.
type ImageInfo struct {
	// Agent Agent name from image label (if any)
	Agent     *string    `json:"agent,omitempty"`
	CreatedAt *time.Time `json:"created_at,omitempty"`

	// FailureMessage Server-side failure message, non-empty only when
	// `status == "failed"`. Surfaces verbatim to the user so
	// ops can diagnose snapshot / push errors. Empty on local
	// sandboxd, which never produces a failed state.
	FailureMessage *string `json:"failure_message,omitempty"`

	// Id Full content-addressable image digest, including its
	// algorithm prefix (e.g. `sha256:abc...`). Stable across
	// the image's lifetime and usable as `name` in
	// `removeImage` and `inspectImage`. UIs that want a short
	// form (Docker's familiar 12-char prefix) can derive it
	// from this value.
	Id *string `json:"id,omitempty"`

	// Progress Optional progress percentage [0, 100] for in-flight
	// prepare work. Best-effort — fields may stay at 0 even for
	// in-progress images on backends that don't model granular
	// progress. Local sandboxd always omits this field.
	Progress   *int    `json:"progress,omitempty"`
	Repository *string `json:"repository,omitempty"`

	// Size Image size in bytes. Pretty-printing ("123 MB") is a UI
	// concern and stays in the CLI; the wire format keeps the
	// value summable / sortable.
	Size *int64 `json:"size,omitempty"`

	// Status Async-prep state for the image. Cloud-side extension to
	// describe templates / images that go through a server-side
	// prepare pipeline (snapshot finalize, registry push,
	// metadata extraction). Local sandboxd reports "completed"
	// for every cached image — there is no in-flight state on
	// the local daemon. Cloud fills this in with the real
	// workflow state so `inspectImage` polling can wait for
	// terminal states.
	Status *ImageInfoStatus `json:"status,omitempty"`
	Tag    *string          `json:"tag,omitempty"`
}

// ImageInfoStatus Async-prep state for the image. Cloud-side extension to
// describe templates / images that go through a server-side
// prepare pipeline (snapshot finalize, registry push,
// metadata extraction). Local sandboxd reports "completed"
// for every cached image — there is no in-flight state on
// the local daemon. Cloud fills this in with the real
// workflow state so `inspectImage` polling can wait for
// terminal states.
type ImageInfoStatus string

// LegacyHealthResponse defines model for LegacyHealthResponse.
type LegacyHealthResponse struct {
	Release bool   `json:"release"`
	Status  string `json:"status"`
	Version string `json:"version"`
}

// LogLevelMap Map of category name to current log-level threshold. Keys are
// category names (e.g. `proxy`, `general`); values are level strings
// accepted by `LogLevelRequest`. Empty when the daemon was built
// without the per-component log-level registry wired up.
type LogLevelMap map[string]string

// LogLevelRequest defines model for LogLevelRequest.
type LogLevelRequest struct {
	// Level Threshold to apply to the target category.
	Level LogLevelRequestLevel `json:"level"`
}

// LogLevelRequestLevel Threshold to apply to the target category.
type LogLevelRequestLevel string

// MessageResponse defines model for MessageResponse.
type MessageResponse struct {
	// Message Human-readable message describing the operation outcome.
	Message string `json:"message"`
}

// NetworkLogEntry defines model for NetworkLogEntry.
type NetworkLogEntry struct {
	CountSince int       `json:"count_since"`
	Host       string    `json:"host"`
	LastSeen   time.Time `json:"last_seen"`
	ProxyType  *string   `json:"proxy_type,omitempty"`
	Reason     *string   `json:"reason,omitempty"`
	Rule       string    `json:"rule"`
	Since      time.Time `json:"since"`
	VmName     string    `json:"vm_name"`
}

// NetworkLogResponse defines model for NetworkLogResponse.
type NetworkLogResponse struct {
	AllowedHosts []NetworkLogEntry `json:"allowed_hosts"`
	BlockedHosts []NetworkLogEntry `json:"blocked_hosts"`
}

// NetworkPolicyDebug Which network policy governs this sandbox. `scope` reflects whether a sandbox-scoped override applies on top of the global policy; `organization`/`organization_unavailable` describe the underlying global policy's governance. Omitted when the policy dimensions can't be resolved — either because no policy manager is wired / the default policy has not been configured yet, or because a transient policy-manager failure (e.g. an error listing policies) prevented resolution. Clients should treat omission as "unknown/undetermined" rather than strictly "not configured".
type NetworkPolicyDebug struct {
	// Organization Organization managing the global policy, when org-managed. Omitted for local-only policy.
	Organization *string `json:"organization,omitempty"`

	// OrganizationUnavailable True when the active-organization lookup failed: governance is in play but the organization name could not be resolved.
	OrganizationUnavailable *bool `json:"organization_unavailable,omitempty"`

	// Scope global = governed by the global policy only; sandbox = a sandbox-scoped override applies on top of the global policy.
	Scope NetworkPolicyDebugScope `json:"scope"`
}

// NetworkPolicyDebugScope global = governed by the global policy only; sandbox = a sandbox-scoped override applies on top of the global policy.
type NetworkPolicyDebugScope string

// OAuthDebugInfo Presence-only view of a proxy's OAuth interception state.
type OAuthDebugInfo struct {
	// Configured True when per-runtime OAuth interception is wired (OAuthConfig and TokenManager both present). This reports only that the interceptor exists, not that OAuth is the credential in effect — see SandboxDebug.auth_mode for the latter.
	Configured bool `json:"configured"`

	// Service OAuth service the interceptor targets (e.g. anthropic, openai).
	Service *string `json:"service,omitempty"`
}

// PolicyRule defines model for PolicyRule.
type PolicyRule struct {
	Decision PolicyRuleDecision `json:"decision"`
	Id       string             `json:"id"`
	Name     *string            `json:"name,omitempty"`

	// Origin Source the rule was loaded from:
	// - "local": configured locally on this machine.
	// - "remote": pushed from a centrally-managed policy source.
	// - "scoped": auto-attached to a single sandbox at create time.
	Origin       *PolicyRuleOrigin `json:"origin,omitempty"`
	Reason       *string           `json:"reason,omitempty"`
	ResourceType string            `json:"resource_type"`
	Resources    []string          `json:"resources"`

	// SandboxName Sandbox this rule is scoped to (matches SandboxInfo.name).
	// Omitted for global rules.
	SandboxName *string           `json:"sandbox_name,omitempty"`
	Status      *PolicyRuleStatus `json:"status,omitempty"`
}

// PolicyRuleDecision defines model for PolicyRule.Decision.
type PolicyRuleDecision string

// PolicyRuleOrigin Source the rule was loaded from:
// - "local": configured locally on this machine.
// - "remote": pushed from a centrally-managed policy source.
// - "scoped": auto-attached to a single sandbox at create time.
type PolicyRuleOrigin string

// PolicyRuleStatus defines model for PolicyRule.Status.
type PolicyRuleStatus string

// PolicyRuleAction A single action against the policy rule set. The `action` field
// discriminates which schema variant applies and which other fields are
// required.
type PolicyRuleAction struct {
	union json.RawMessage
}

// PolicyRuleActionAllow defines model for PolicyRuleActionAllow.
type PolicyRuleActionAllow struct {
	Action    PolicyRuleActionAllowAction `json:"action"`
	Resources []string                    `json:"resources"`

	// SandboxName Scope this action to a specific sandbox (matches SandboxInfo.name). Omitted for global rules.
	SandboxName *string `json:"sandbox_name,omitempty"`
}

// PolicyRuleActionAllowAction defines model for PolicyRuleActionAllow.Action.
type PolicyRuleActionAllowAction string

// PolicyRuleActionDeny defines model for PolicyRuleActionDeny.
type PolicyRuleActionDeny struct {
	Action    PolicyRuleActionDenyAction `json:"action"`
	Resources []string                   `json:"resources"`

	// SandboxName Scope this action to a specific sandbox (matches SandboxInfo.name). Omitted for global rules.
	SandboxName *string `json:"sandbox_name,omitempty"`
}

// PolicyRuleActionDenyAction defines model for PolicyRuleActionDeny.Action.
type PolicyRuleActionDenyAction string

// PolicyRuleActionRemoveID defines model for PolicyRuleActionRemoveID.
type PolicyRuleActionRemoveID struct {
	Action PolicyRuleActionRemoveIDAction `json:"action"`

	// Id Rule ID to remove.
	Id string `json:"id"`

	// SandboxName Scope this action to a specific sandbox (matches SandboxInfo.name). Omitted for global rules.
	SandboxName *string `json:"sandbox_name,omitempty"`
}

// PolicyRuleActionRemoveIDAction defines model for PolicyRuleActionRemoveID.Action.
type PolicyRuleActionRemoveIDAction string

// PolicyRuleActionRemoveResource defines model for PolicyRuleActionRemoveResource.
type PolicyRuleActionRemoveResource struct {
	Action    PolicyRuleActionRemoveResourceAction `json:"action"`
	Resources []string                             `json:"resources"`

	// SandboxName Scope this action to a specific sandbox (matches SandboxInfo.name). Omitted for global rules.
	SandboxName *string `json:"sandbox_name,omitempty"`
}

// PolicyRuleActionRemoveResourceAction defines model for PolicyRuleActionRemoveResource.Action.
type PolicyRuleActionRemoveResourceAction string

// PolicyRuleResult defines model for PolicyRuleResult.
type PolicyRuleResult struct {
	// Action Echoes the action that produced this result — same set as
	// the discriminator on PolicyRuleAction so generated clients
	// can exhaustively switch over results.
	Action    PolicyRuleResultAction `json:"action"`
	Created   *[]CreatedRule         `json:"created,omitempty"`
	Error     *string                `json:"error,omitempty"`
	Existing  *[]ExistingResource    `json:"existing,omitempty"`
	Id        *string                `json:"id,omitempty"`
	Resources *[]string              `json:"resources,omitempty"`

	// SandboxName Sandbox this action was scoped to (matches SandboxInfo.name). Omitted for global rules.
	SandboxName *string `json:"sandbox_name,omitempty"`
}

// PolicyRuleResultAction Echoes the action that produced this result — same set as
// the discriminator on PolicyRuleAction so generated clients
// can exhaustively switch over results.
type PolicyRuleResultAction string

// PolicyRulesListResponse defines model for PolicyRulesListResponse.
type PolicyRulesListResponse struct {
	LastSyncedMessage       *string                                  `json:"last_synced_message,omitempty"`
	LastSyncedStatus        *PolicyRulesListResponseLastSyncedStatus `json:"last_synced_status,omitempty"`
	Organization            *string                                  `json:"organization,omitempty"`
	OrganizationUnavailable *bool                                    `json:"organization_unavailable,omitempty"`
	Rules                   []PolicyRule                             `json:"rules"`
}

// PolicyRulesListResponseLastSyncedStatus defines model for PolicyRulesListResponse.LastSyncedStatus.
type PolicyRulesListResponseLastSyncedStatus string

// PolicyRulesRequest defines model for PolicyRulesRequest.
type PolicyRulesRequest struct {
	Actions []PolicyRuleAction `json:"actions"`
}

// PolicyRulesResponse defines model for PolicyRulesResponse.
type PolicyRulesResponse struct {
	Results []PolicyRuleResult `json:"results"`
}

// PolicySetupRequest defines model for PolicySetupRequest.
type PolicySetupRequest struct {
	Preset PolicySetupRequestPreset `json:"preset"`
}

// PolicySetupRequestPreset defines model for PolicySetupRequest.Preset.
type PolicySetupRequestPreset string

// PolicySetupResponse defines model for PolicySetupResponse.
type PolicySetupResponse struct {
	AlreadyConfigured *bool                              `json:"already_configured,omitempty"`
	Applied           bool                               `json:"applied"`
	ExistingPreset    *PolicySetupResponseExistingPreset `json:"existing_preset,omitempty"`
}

// PolicySetupResponseExistingPreset defines model for PolicySetupResponse.ExistingPreset.
type PolicySetupResponseExistingPreset string

// PolicySetupStatusResponse defines model for PolicySetupStatusResponse.
type PolicySetupStatusResponse struct {
	// Needed True when first-run policy selection is needed
	Needed bool `json:"needed"`
}

// PortKey Identifies one or more published-port bindings on a sandbox for
// the purpose of unpublishing them. The key is the *container*
// side: `sandbox_port` (and optionally `protocol`) is what the
// user actually thinks about — "I'm done exposing container port
// 3000". The host-side fields are present as optional
// disambiguators for the unusual case where a sandbox port has
// multiple host-side bindings; pass them only when you need to
// narrow the match.
//
// Match semantics (used by `unpublishPorts`):
//   - the daemon enumerates the sandbox's currently-published
//     ports and removes every entry whose fields equal every
//     field provided in the key;
//   - missing optional fields don't all behave the same. See
//     each field's `description` for the exact rule: `protocol`
//     defaults to `tcp`, `host_ip` expands to the dual-stack
//     loopback pair (symmetric with `publishPorts` — NOT a true
//     wildcard), and `host_port` is a true wildcard;
//   - matching zero entries is a no-op success (the operation is
//     idempotent — declared end state, not a delta).
type PortKey struct {
	// HostIp Restrict the match to bindings on this host IP. When
	// omitted the key matches the same dual-stack loopback pair
	// (`127.0.0.1` and `::1`) that a `host_ip`-less publish
	// would have used — symmetric with `publishPorts`. To target
	// a routable binding (e.g. one published on `0.0.0.0` or a
	// specific NIC) supply the IP explicitly; an omitted
	// `host_ip` will not match it.
	HostIp *string `json:"host_ip,omitempty"`

	// HostPort Restrict the match to a specific host-side port (e.g. when
	// an auto-assigned binding needs to be removed by its
	// published value, available from `listPublishedPorts`).
	// Omit to match every host port.
	HostPort *int `json:"host_port,omitempty"`

	// Protocol Protocol of the binding. Defaults to "tcp" when omitted —
	// sufficient for the common case of one tcp binding per
	// container port.
	Protocol *PortKeyProtocol `json:"protocol,omitempty"`

	// SandboxPort Container port whose binding(s) should be removed.
	SandboxPort int `json:"sandbox_port"`
}

// PortKeyProtocol Protocol of the binding. Defaults to "tcp" when omitted —
// sufficient for the common case of one tcp binding per
// container port.
type PortKeyProtocol string

// PortPublishRequest defines model for PortPublishRequest.
type PortPublishRequest struct {
	HostIp *string `json:"host_ip,omitempty"`

	// HostPort Host port to publish on (0 means auto-assign)
	HostPort int                         `json:"host_port"`
	Protocol *PortPublishRequestProtocol `json:"protocol,omitempty"`

	// SandboxPort Container port to publish (1-65535)
	SandboxPort int `json:"sandbox_port"`
}

// PortPublishRequestProtocol defines model for PortPublishRequest.Protocol.
type PortPublishRequestProtocol string

// PortReplaceDesiredRequest Replaces a saved publish intent matched by `old` with the publish
// request in `new`. The replacement is replayed by the next
// `startSandbox` call.
type PortReplaceDesiredRequest struct {
	New PortPublishRequest `json:"new"`

	// Old Identifies the saved publish intent to replace. The key uses
	// the same shape as unpublish, but it matches persisted desired
	// port state rather than currently-published live bindings.
	Old PortKey `json:"old"`
}

// PortReplayConflict Details for a `port_replay_conflict` error returned by
// `POST /sandbox/{name}/start`. Sandboxes remember published-port
// requests so they can be restored after the sandbox stops or the
// daemon restarts. When a remembered request used an explicit host
// port and that port is already in use during start, sandboxd leaves
// the sandbox stopped and returns this payload so clients can offer
// to replace the saved desired mapping with a different host port
// before retrying `startSandbox`.
type PortReplayConflict struct {
	// HostIp Host IP from the persisted publish request. Empty means the default loopback bindings.
	HostIp *string `json:"host_ip,omitempty"`

	// HostPort Explicit host port that could not be rebound.
	HostPort int `json:"host_port"`

	// Protocol Protocol from the persisted publish request.
	Protocol string `json:"protocol"`

	// RequestIndex Index of the persisted publish request that failed during start replay.
	RequestIndex int `json:"request_index"`

	// SandboxPort Sandbox port the host port maps to.
	SandboxPort int `json:"sandbox_port"`
}

// PublishedPort defines model for PublishedPort.
type PublishedPort struct {
	HostIp   string `json:"host_ip"`
	HostPort int    `json:"host_port"`

	// Protocol Same enum as PortPublishRequest.protocol — kept symmetric so
	// generated clients can exhaustively switch on protocol values
	// from either side of the wire.
	Protocol    PublishedPortProtocol `json:"protocol"`
	SandboxPort int                   `json:"sandbox_port"`
}

// PublishedPortProtocol Same enum as PortPublishRequest.protocol — kept symmetric so
// generated clients can exhaustively switch on protocol values
// from either side of the wire.
type PublishedPortProtocol string

// RegistryCredential Per-sandbox registry credential, used by the daemon to materialize a
// Docker `~/.docker/config.json` inside the sandbox so dockerd-in-DinD
// can authenticate to private registries (the host network proxy is
// not on that path). The client builds this list from its own
// credential store — sandbox-scoped binds win on hostname clash,
// the "all sandboxes" bucket fills the rest, host-only ("_") scope
// is excluded.
type RegistryCredential struct {
	// Hostname Registry hostname (e.g. "ghcr.io", "registry.gitlab.com").
	Hostname string `json:"hostname"`

	// Secret Password or token paired with `username`.
	Secret string `json:"secret"`

	// Username Username paired with `secret` for HTTP Basic. The client
	// substitutes `x-access-token` for empty / `<token>` placeholders
	// before shipping, so the daemon does not have to re-derive the
	// convention.
	Username string `json:"username"`
}

// ResetResponse defines model for ResetResponse.
type ResetResponse struct {
	// Pid PID of the daemon process (which is shutting down). The client can wait for this process to exit before proceeding.
	Pid int `json:"pid"`

	// SandboxesStopped Names of sandboxes the daemon attempted to stop and remove (best
	// effort). The daemon performs each step of per-sandbox cleanup
	// individually, logging and continuing on errors, so a name appearing
	// here means the runtime was removed from the daemon's in-memory
	// registry — it does not guarantee every sub-step succeeded.
	SandboxesStopped []string `json:"sandboxes_stopped"`
}

// RuntimeVersions Versions of the daemon's runtime components. Each component
// carries a `_version` and `_commit` so callers don't have to
// special-case the shape — fields are optional because not every
// runtime exposes both.
type RuntimeVersions struct {
	DockerNextCommit  *string `json:"docker_next_commit,omitempty"`
	DockerNextVersion *string `json:"docker_next_version,omitempty"`

	// ShimVersion nerdbox shim version
	ShimVersion *string `json:"shim_version,omitempty"`

	// VmmCommit VMM (sailor) commit
	VmmCommit *string `json:"vmm_commit,omitempty"`
}

// SandboxCreateRequest defines model for SandboxCreateRequest.
type SandboxCreateRequest struct {
	// AdditionalWorkspaces Additional workspace directories mounted alongside the
	// primary workspace. Same name as SandboxInfo.additional_workspaces
	// on the response side.
	AdditionalWorkspaces *[]WorkspaceMount `json:"additional_workspaces,omitempty"`

	// Agent Agent type (e.g. "claude", "codex", "cursor")
	Agent string `json:"agent"`

	// AgentOptions Agent-specific options, keyed by agent name. Each agent —
	// built-in or installed via a kit — defines its own option
	// schema; the daemon consults `agent_options[<agent>]` where
	// `<agent>` matches this request's `agent` field, and ignores
	// entries for any other agent.
	//
	// Strictness: the daemon is lenient. Entries whose key
	// doesn't match the request's `agent` are silently dropped.
	// Unknown keys *within* the matching agent's bag are also
	// ignored — kit-installed agents own their own validation,
	// and the daemon can't statically enumerate their options.
	// Real bugs (typos in option keys) surface as the option
	// having no effect. A server-side options-schema endpoint
	// (`GET /daemon/agents`) is deferred — the daemon resolves
	// built-in agents from its embedded blueprint registry and
	// kit-supplied options are validated by the kit author's
	// agent implementation.
	//
	// Built-in option keys today:
	//   claude:
	//     patch_settings (boolean) — intercept Claude API
	//       responses to remove `disableBypassPermissionsMode`.
	//
	// Agents installed via kits may define additional keys; see
	// the kit's documentation.
	AgentOptions *map[string]map[string]interface{} `json:"agent_options,omitempty"`

	// BindingsPath Absolute path to the user's credentials.yaml (the client's
	// resolved config-home location, e.g. $XDG_CONFIG_HOME/sbx/
	// credentials.yaml). The daemon reads binding authorization from
	// this file to decide which v2 credentials it may inject; it does
	// NOT fall back to its own process environment, which may differ
	// from the user's. Local-deployment only — a future cloud/multi-
	// tenant path replaces this with a verified authorization token.
	BindingsPath *string `json:"bindings_path,omitempty"`

	// Clone When true, runs the agent on a private in-container clone
	// of the host Git repository instead of bind-mounting the
	// workspace directly. The host repository is mounted
	// read-only at `/run/sandbox/source` inside the sandbox; the
	// agent's commits live in the clone and are accessible via
	// the `sandbox-<name>` Git remote configured on the host
	// repo. The daemon detects the Git root from `workspace` at
	// create time, and returns 400 when:
	//   - `workspace` is not inside a Git repository,
	//   - the resolved root is itself a Git worktree (the
	//     in-container `git clone --reference` cannot follow a
	//     worktree's `.git` pointer through the read-only mount),
	//   - the root's `.git` is not a real directory (submodule or
	//     `--separate-git-dir` setups).
	// The resulting sandbox is surfaced via
	// `SandboxInfo.source_repo_dir` (the host Git root) and the
	// `com.docker.sandbox.cloneMode` container label.
	Clone *bool `json:"clone,omitempty"`

	// Cpus CPU limit, in whole CPUs. 0 (the default) means auto: the daemon
	// allocates all host CPUs (runtime.NumCPU()).
	// Fractional CPU shares are not supported — use a whole number.
	Cpus *int `json:"cpus,omitempty"`

	// CredentialValues Environment-based credential values from the client's shell.
	// The daemon cannot access shell env vars, so the client reads
	// them and passes the values here.
	CredentialValues *[]CredentialValue `json:"credential_values,omitempty"`

	// Detached When true, the sandbox runs in detached mode: the daemon
	// skips auto-stop on the last sentinel disconnect, so the
	// sandbox keeps running after the `sbx run -d ...` invocation
	// exits. The user is responsible for stopping it (sbx stop /
	// sbx rm). Matches the legacy Spec.Detached semantics.
	Detached *bool `json:"detached,omitempty"`

	// DindVolumeSize Human-friendly size string for a DinD sandbox's
	// /var/lib/docker block-backed volume (e.g. "10g", "512m").
	// Empty selects the underlying default (~50 GB). The CLI
	// reads DOCKER_SANDBOXES_DOCKER_SIZE from the user's shell
	// env and passes the value through on this field — the daemon's
	// process env doesn't see the CLI's env.
	DindVolumeSize *string `json:"dind_volume_size,omitempty"`

	// Display Experimental. When true, the daemon stamps
	// com.docker.sandbox.display=wayland on the container at create
	// time; docker-next ≥ v0.6.0 reads that label and provisions a
	// wayland display socket inside the sandbox.
	//
	// Default false. This is a host-capability exposure (each
	// display-enabled sandbox can draw windows on the host
	// compositor and could spoof UI), so opt-in is per-sandbox via
	// the CLI's `--display` flag, not a global setting.
	Display *bool `json:"display,omitempty"`

	// EnableVirtiofsCache When true, opts this sandbox into virtiofs caching for its
	// bind-mounted workspace paths. Disabled by default while the
	// underlying feature is still rolling out. The CLI reads
	// DOCKER_SANDBOXES_ENABLE_VIRTIOFS_CACHE=1 from the user's
	// shell env and passes the resulting boolean here — the
	// daemon's process env doesn't see the CLI's env.
	EnableVirtiofsCache *bool `json:"enable_virtiofs_cache,omitempty"`

	// Environment Additional environment variables (TERM, TZ, etc.)
	Environment *map[string]string `json:"environment,omitempty"`

	// KitArtifacts Composed kit content shipped inline by clients that
	// resolved `--kit` references locally. Each entry is the
	// JSON-marshalled form of a `sandboxlib/kit.Artifact` (which
	// embeds `spec.Artifact` from `docker/sbx-kits-contrib`).
	// The daemon `json.Unmarshal`s each entry back into
	// `kit.Artifact`, runs `kit.Compose` against the base agent
	// resolved from `agent`, and applies the resulting
	// customizers (file copies, install / startup commands,
	// network policy, credential sources, mounts, env vars).
	//
	// The daemon does not resolve kit references on its own —
	// the client carries the resolved content. The free-form
	// object shape mirrors the source struct's JSON tags; both
	// sides round-trip through `encoding/json`.
	KitArtifacts *[]map[string]interface{} `json:"kit_artifacts,omitempty"`

	// Kits Kit paths or names to compose into the sandbox. Currently
	// rejected by the daemon — the daemon cannot resolve refs
	// on its own (no OCI pull, no git clone, no filesystem
	// access outside its state dir). Clients that resolved
	// their kits locally should ship the parsed content via
	// `kit_artifacts` instead. Kept on the wire for the
	// in-flight CLI/TUI eligibility check that routes
	// kit-bearing requests to the legacy create path.
	Kits *[]string `json:"kits,omitempty"`

	// Memory Memory limit (e.g. "8g")
	Memory *string `json:"memory,omitempty"`

	// Name Sandbox name (auto-generated if omitted)
	Name *string `json:"name,omitempty"`

	// Profile Name of the policy profile to assign to this sandbox. The
	// daemon's governance layer reads the profile when evaluating
	// mount and network rules; empty (the common case) selects
	// the default profile. Surfaced on responses as
	// SandboxInfo.profile.
	Profile *string `json:"profile,omitempty"`

	// PullPolicy Image pull policy:
	// - "always": pull before creating (default)
	// - "missing": skip if image exists locally
	// - "never": fail if image not local
	PullPolicy *SandboxCreateRequestPullPolicy `json:"pull_policy,omitempty"`

	// RegistryCredentials Registry credentials the daemon must inject as
	// `/home/agent/.docker/config.json` inside the sandbox at mode
	// 0600, so `docker pull <private-host>/...` from inside the
	// sandbox can authenticate. The CLI builds the list from its
	// credential store, merging the per-sandbox bucket
	// (higher priority on hostname clash) with the
	// `AllSandboxesRegistryScope` bucket and excluding host-only
	// (`"_"` scope) credentials. Empty means no config.json is
	// written.
	RegistryCredentials *[]RegistryCredential `json:"registry_credentials,omitempty"`

	// SecretsScope Scope for credential store lookups
	SecretsScope *string `json:"secrets_scope,omitempty"`

	// Template Template image reference (agent default if omitted)
	Template *string `json:"template,omitempty"`

	// Workspace Absolute path to the primary workspace on the host
	Workspace string `json:"workspace"`
}

// SandboxCreateRequestPullPolicy Image pull policy:
// - "always": pull before creating (default)
// - "missing": skip if image exists locally
// - "never": fail if image not local
type SandboxCreateRequestPullPolicy string

// SandboxCreateResponse defines model for SandboxCreateResponse.
type SandboxCreateResponse struct {
	Agent    string                      `json:"agent"`
	Name     string                      `json:"name"`
	Status   SandboxCreateResponseStatus `json:"status"`
	Warnings *[]string                   `json:"warnings,omitempty"`

	// Withheld Service identifiers whose v2 credential the daemon withheld
	// because no binding authorized it (the credential was not
	// injected; the sandbox still started). Service names only — no
	// values, paths, or domains. Empty/omitted when nothing was
	// withheld.
	Withheld *[]string `json:"withheld,omitempty"`

	// Workspace Effective workspace path mounted into the sandbox. When the
	// sandbox is backed by a git worktree, this is the worktree
	// path; otherwise it's the directory the user supplied. The
	// user-supplied directory in the worktree case is reported via
	// `worktree.original_workspace`.
	Workspace string `json:"workspace"`

	// Worktree Legacy metadata about a host-side git worktree backing a
	// sandbox. The CLI's `--branch` flag (which created host-side
	// worktrees) has been removed in favour of `--clone` (in-container
	// clone, signalled via `SandboxInfo.source_repo_dir`). This field
	// is populated only for sandboxes created by older CLI versions
	// and is not produced by new sandboxes — it is retained on
	// `SandboxInfo` / `SandboxCreateResponse` so inspecting a
	// legacy worktree-backed sandbox still works.
	Worktree *SandboxWorktree `json:"worktree,omitempty"`
}

// SandboxCreateResponseStatus defines model for SandboxCreateResponse.Status.
type SandboxCreateResponseStatus string

// SandboxDebug defines model for SandboxDebug.
type SandboxDebug struct {
	// AgentName Coding agent running in this runtime.
	AgentName string `json:"agent_name"`

	// AuthMode Credential the proxy's OAuth engine would actually inject for the agent's service right now, distinct from oauth.configured (which only reports that interception is wired). A per-VM API key takes precedence over the OAuth token, so a configured OAuth interceptor can still report auth_mode=api_key. Omitted when no OAuth-capable interceptor is wired for the runtime. Presence-only and non-mutating — it never triggers a token refresh.
	AuthMode *SandboxDebugAuthMode `json:"auth_mode,omitempty"`

	// CustomSecrets Custom placeholder->secret mappings injected into this sandbox (classification-only, no values).
	CustomSecrets []CustomSecretDebugEntry `json:"custom_secrets"`

	// DispatchCacheVersion Cache fingerprint at the last dispatcher invocation, if any.
	DispatchCacheVersion *string `json:"dispatch_cache_version,omitempty"`

	// HasProxyState Whether sandboxd is tracking proxy state for this runtime.
	HasProxyState bool `json:"has_proxy_state"`

	// Id Daemon-assigned runtime UUID.
	Id string `json:"id"`

	// Image Image reference that the sandbox's backing container is running, e.g. "docker/sandbox-templates-claude-code:0.0.1". Sourced from the Docker container scan and omitted when the container can't be matched (e.g. the container is absent).
	Image *string `json:"image,omitempty"`

	// ImageDigest Content digest of the running image (e.g. "sha256:..."), as reported by the Docker daemon. Omitted when the backing container can't be matched.
	ImageDigest *string `json:"image_digest,omitempty"`

	// McpGatewayPresent Whether an MCP gateway is active for this runtime.
	McpGatewayPresent bool `json:"mcp_gateway_present"`

	// MountPolicyDenied True when this sandbox's workspace mounts are currently denied by mount policy (e.g. an organization admin blocked a path the sandbox uses). The sandbox is kept visible and removable but cannot be started until the policy allows the path again. Evaluated at daemon load and cleared on a successful start, so it reflects policy as of the last daemon start / start attempt. Absent/false in the common case.
	MountPolicyDenied *bool `json:"mount_policy_denied,omitempty"`

	// Name Runtime (sandbox) name.
	Name string `json:"name"`

	// NetworkName Sanitized Docker (gvisor) network name for this runtime.
	NetworkName string `json:"network_name"`

	// NetworkPolicy Which network policy governs this sandbox. `scope` reflects whether a sandbox-scoped override applies on top of the global policy; `organization`/`organization_unavailable` describe the underlying global policy's governance. Omitted when the policy dimensions can't be resolved — either because no policy manager is wired / the default policy has not been configured yet, or because a transient policy-manager failure (e.g. an error listing policies) prevented resolution. Clients should treat omission as "unknown/undetermined" rather than strictly "not configured".
	NetworkPolicy *NetworkPolicyDebug `json:"network_policy,omitempty"`

	// Oauth Presence-only view of a proxy's OAuth interception state.
	Oauth OAuthDebugInfo `json:"oauth"`

	// ProxyAddr Local address the runtime's network proxy is listening on, if a proxy is wired.
	ProxyAddr *string `json:"proxy_addr,omitempty"`

	// PublishedPortCount Number of host ports currently published for this runtime.
	PublishedPortCount int `json:"published_port_count"`

	// Secrets Secrets injected into this sandbox (classification-only, no values).
	Secrets []SecretDebugEntry `json:"secrets"`

	// SessionCount Active sentinel session count (drives auto-stop).
	SessionCount int `json:"session_count"`
}

// SandboxDebugAuthMode Credential the proxy's OAuth engine would actually inject for the agent's service right now, distinct from oauth.configured (which only reports that interception is wired). A per-VM API key takes precedence over the OAuth token, so a configured OAuth interceptor can still report auth_mode=api_key. Omitted when no OAuth-capable interceptor is wired for the runtime. Presence-only and non-mutating — it never triggers a token refresh.
type SandboxDebugAuthMode string

// SandboxInfo defines model for SandboxInfo.
type SandboxInfo struct {
	AdditionalWorkspaces *[]WorkspaceMount `json:"additional_workspaces,omitempty"`
	Agent                *string           `json:"agent,omitempty"`
	CreatedAt            *time.Time        `json:"created_at,omitempty"`

	// Id Daemon-assigned runtime identifier (a UUID), stable across
	// daemon restarts. Returned in `sbx ls --json`; the human
	// `sbx ls` table does not show an ID column for local sandboxes.
	// Empty only for legacy runtimes persisted before the daemon
	// assigned UUIDs, or from a daemon that predates this field.
	// Distinct from the cloud `sbx_*` sandbox ID, which the cloud
	// list path carries out-of-band rather than through this local
	// wire type.
	Id string `json:"id"`

	// Labels Container labels recorded at create time
	// (`com.docker.sandbox.*` plus anything else the user or a
	// kit added). Carries the runtime metadata callers need to
	// determine workspace path, worktree mode, clone-mode flag,
	// git root, original workspace, and display surface without
	// inspecting the container directly. Individual keys may be
	// absent on older sandboxes whose labels predate them —
	// callers should tolerate missing keys rather than assume
	// every key is always populated.
	Labels *map[string]string `json:"labels,omitempty"`

	// MountPolicyDenied True when the sandbox's workspace mounts are currently denied by
	// mount policy (e.g. an organization admin blocked a path the
	// sandbox uses). The sandbox is kept visible in `sbx ls` and is
	// removable via `sbx rm`, but cannot be started until the policy
	// allows the path again. Absent/false in the common case. Evaluated
	// at daemon load and cleared on a successful start, so it reflects
	// policy as of the last daemon start / start attempt rather than
	// being re-evaluated on every list.
	MountPolicyDenied *bool            `json:"mount_policy_denied,omitempty"`
	Name              string           `json:"name"`
	Ports             *[]PublishedPort `json:"ports,omitempty"`

	// Profile Name of the policy profile the sandbox was created with.
	// Empty when the sandbox doesn't reference a policy profile
	// (the common case). Surfaced in `sbx ls --show-profiles`
	// and similar UX; not used for any wire-level routing.
	Profile *string `json:"profile,omitempty"`

	// SourceRepoDir Host Git root bind-mounted read-only into the sandbox at
	// `/run/sandbox/source` for clone-mode sandboxes (`--clone`).
	// Empty/absent for direct-mount and legacy worktree sandboxes.
	// Presence is the canonical wire-level signal that the
	// sandbox runs on an in-container `git clone --reference`
	// and that removing it discards any uncommitted/unpushed
	// in-container Git state (see `LabelKeyCloneMode`).
	SourceRepoDir *string           `json:"source_repo_dir,omitempty"`
	Status        SandboxInfoStatus `json:"status"`

	// Workspace Effective workspace path mounted into the sandbox. Same
	// semantics as `SandboxCreateResponse.workspace` — equals the
	// worktree path when worktree-backed, the user-supplied
	// directory otherwise.
	Workspace string `json:"workspace"`

	// Worktree Legacy metadata about a host-side git worktree backing a
	// sandbox. The CLI's `--branch` flag (which created host-side
	// worktrees) has been removed in favour of `--clone` (in-container
	// clone, signalled via `SandboxInfo.source_repo_dir`). This field
	// is populated only for sandboxes created by older CLI versions
	// and is not produced by new sandboxes — it is retained on
	// `SandboxInfo` / `SandboxCreateResponse` so inspecting a
	// legacy worktree-backed sandbox still works.
	Worktree *SandboxWorktree `json:"worktree,omitempty"`
}

// SandboxInfoStatus defines model for SandboxInfo.Status.
type SandboxInfoStatus string

// SandboxWorktree Legacy metadata about a host-side git worktree backing a
// sandbox. The CLI's `--branch` flag (which created host-side
// worktrees) has been removed in favour of `--clone` (in-container
// clone, signalled via `SandboxInfo.source_repo_dir`). This field
// is populated only for sandboxes created by older CLI versions
// and is not produced by new sandboxes — it is retained on
// `SandboxInfo` / `SandboxCreateResponse` so inspecting a
// legacy worktree-backed sandbox still works.
type SandboxWorktree struct {
	// Branch Branch the worktree was created on.
	Branch string `json:"branch"`

	// OriginalWorkspace The user's actual workspace directory. The path at the
	// sibling `workspace` field is the worktree mount; this field
	// points back to the underlying directory the worktree
	// represents.
	OriginalWorkspace string `json:"original_workspace"`
}

// SaveRequest defines model for SaveRequest.
type SaveRequest struct {
	// Description Optional human-readable description of the saved image.
	// Cloud-only extension to the save flow; local sandboxd accepts
	// the field for spec parity and ignores it. The unified spec
	// stays the single source of truth for "what can be sent" —
	// see contract-mirror.md in sbx-cloud for the rationale.
	Description *string `json:"description,omitempty"`

	// Tag Image tag (e.g. "myimage:v1.0")
	Tag string `json:"tag"`
}

// SaveResponse defines model for SaveResponse.
type SaveResponse struct {
	ImageId *string `json:"image_id,omitempty"`
	Tag     *string `json:"tag,omitempty"`
}

// SecretDebugEntry A single injected service credential, classification-only.
type SecretDebugEntry struct {
	// Class Value classification — populated, empty, whitespace, or unknown.
	Class string `json:"class"`

	// EnvVarName Environment variable name for env-backed sources only. File paths are never reported.
	EnvVarName *string `json:"env_var_name,omitempty"`
	Revoked    bool    `json:"revoked"`
	Service    string  `json:"service"`

	// SourceType One of "uploaded", "env", "file", or "".
	SourceType string `json:"source_type"`

	// Value Always the censored placeholder "***".
	Value string `json:"value"`
}

// ShutdownResponse defines model for ShutdownResponse.
type ShutdownResponse struct {
	Message *string `json:"message,omitempty"`

	// Pid PID of the daemon process (which is shutting down). The client can wait for this process to exit before proceeding.
	Pid int `json:"pid"`
}

// SocketPathInfo defines model for SocketPathInfo.
type SocketPathInfo struct {
	// ContainerdTtrpcBytes Canonical byte length of containerd's TTRPC socket
	// (<stateDir>/containerd/containerd.sock.ttrpc). Checked at
	// daemon startup by shortenStateDirIfNeeded; first thing to
	// trip on long paths.
	ContainerdTtrpcBytes *int `json:"containerd_ttrpc_bytes,omitempty"`

	// GvisorSocketDirChosenBytes Canonical byte length of the gvisor per-endpoint socket
	// directory actually configured on the running docker-next
	// server. The daemon picks between the primary candidate
	// (`~/.sbx/run`) and the `os.TempDir()/gvisor` fallback at
	// startup based on which fits the sun_path budget
	// (`resolveGvisorRootDir` in sandboxd/daemon.go). Omitted
	// when docker-next has not been configured yet (e.g. the
	// partial-error path where `info` is empty).
	GvisorSocketDirChosenBytes *int `json:"gvisor_socket_dir_chosen_bytes,omitempty"`

	// GvisorSocketDirPrimaryBytes Canonical byte length of the *primary* gvisor per-endpoint
	// socket directory candidate (`~/.sbx/run` plus any --app-name
	// suffix), regardless of whether the daemon actually chose it.
	// Highest-risk field: macOS expands /Users → /private/Users
	// (+8 bytes), which has silently pushed long-username
	// deployments past the limit in the past. Compare against
	// `gvisor_socket_dir_chosen_bytes`: when they differ, the
	// daemon fell back to the temp dir because the primary
	// blew the sun_path budget at startup.
	GvisorSocketDirPrimaryBytes *int `json:"gvisor_socket_dir_primary_bytes,omitempty"`

	// StateDirBytes Canonical byte length of the daemon's state directory
	// (`storagepaths.ResolveStateDir`). All sandboxd-managed
	// socket paths derive from this; longer values reduce the
	// margin every shim socket has under the sun_path limit.
	StateDirBytes *int `json:"state_dir_bytes,omitempty"`

	// SunPathLimitBytes Kernel AF_UNIX sockaddr_un.sun_path limit on this platform
	// (104 on macOS, 108 on Linux and Windows; 0 on other
	// platforms). Windows reports 108 because sandboxd still binds
	// an AF_UNIX-style containerd TTRPC socket there
	// (`shortenStateDirIfNeeded` enforces this budget at daemon
	// startup). Compare each *_bytes field below against
	// (limit - 1) to spot an imminent ENAMETOOLONG on bind/connect.
	SunPathLimitBytes int `json:"sun_path_limit_bytes"`

	// UsernameBytes Byte length (not rune count) of os/user.Current().Username
	// with USER / USERNAME / LOGNAME fallback. Multibyte usernames
	// consume more sun_path bytes than their visible character
	// count suggests.
	UsernameBytes *int `json:"username_bytes,omitempty"`
}

// StoredCredentialDebug Identity of a stored service credential. Carries no value.
type StoredCredentialDebug struct {
	// Scope Sandbox name, or "_" for the global/default scope.
	Scope string `json:"scope"`

	// Service External service the credential targets (e.g. github, anthropic).
	Service string `json:"service"`
}

// StoredCustomSecretDebug Identity of a stored custom secret. Carries no value.
type StoredCustomSecretDebug struct {
	// Scope Sandbox name, or "_" for the global/default scope.
	Scope string `json:"scope"`

	// Sentinel Placeholder key (not secret material).
	Sentinel string `json:"sentinel"`
}

// StoredSecretsDebug Read-only view of what is persisted in the host credential store (keychain or encrypted file). Presence/identity only — never contains secret values.
type StoredSecretsDebug struct {
	// Credentials Stored service credentials, identified by scope and service only (no values).
	Credentials []StoredCredentialDebug `json:"credentials"`

	// CustomSecrets Stored custom secrets, identified by scope and sentinel only. Target and env-var metadata live in the encrypted payload and are not reported here to avoid decrypting.
	CustomSecrets []StoredCustomSecretDebug `json:"custom_secrets"`

	// OauthTokenManagers Registry-level OAuth token managers (presence-only, no token material).
	OauthTokenManagers []TokenManagerDebug `json:"oauth_token_managers"`
}

// SyncCredentialsRequest defines model for SyncCredentialsRequest.
type SyncCredentialsRequest struct {
	// BindingsPath Absolute path to the user's credentials.yaml (the client's
	// resolved config-home location, e.g. $XDG_CONFIG_HOME/sbx/
	// credentials.yaml). The daemon reads binding authorization from
	// this file to decide which v2 credentials it may inject; it does
	// NOT fall back to its own process environment, which may differ
	// from the user's. Local-deployment only — a future cloud/multi-
	// tenant path replaces this with a verified authorization token.
	BindingsPath     *string            `json:"bindings_path,omitempty"`
	CredentialValues *[]CredentialValue `json:"credential_values,omitempty"`

	// CustomSecrets Custom secret mappings to install on the sandbox. The daemon
	// keeps the value for target-bound replacement in the proxy;
	// the sandbox process only ever sees `env_name=sentinel` so
	// the secret value never reaches the container.
	//
	// Sentinels must be non-empty and unique within the request —
	// duplicates and empty values are rejected with 400.
	CustomSecrets *[]CustomSecretValue `json:"custom_secrets,omitempty"`
}

// SyncCredentialsResult defines model for SyncCredentialsResult.
type SyncCredentialsResult struct {
	// Message Human-readable message describing the operation outcome.
	Message string `json:"message"`

	// Withheld Service identifiers whose v2 credential the daemon withheld at
	// sync because no binding authorized it. Service names only — no
	// values, paths, or domains. Empty/omitted when nothing was withheld.
	Withheld *[]string `json:"withheld,omitempty"`
}

// TokenManagerDebug Presence-only view of an OAuth token manager. Carries no token material.
type TokenManagerDebug struct {
	Expired bool `json:"expired"`

	// ExpiresAt RFC3339 expiry; omitted when no expiry is set.
	ExpiresAt       *string `json:"expires_at,omitempty"`
	HasAccessToken  bool    `json:"has_access_token"`
	HasClientId     bool    `json:"has_client_id"`
	HasClientSecret bool    `json:"has_client_secret"`
	HasIdToken      bool    `json:"has_id_token"`
	HasRefreshToken bool    `json:"has_refresh_token"`
	ScopesPresent   bool    `json:"scopes_present"`
	Service         string  `json:"service"`
}

// VersionCheckRequest defines model for VersionCheckRequest.
type VersionCheckRequest struct {
	Release *bool   `json:"release,omitempty"`
	Version *string `json:"version,omitempty"`
}

// VersionCheckResponse defines model for VersionCheckResponse.
type VersionCheckResponse struct {
	Result VersionCheckResponseResult `json:"result"`
}

// VersionCheckResponseResult defines model for VersionCheckResponse.Result.
type VersionCheckResponseResult string

// WorkspaceMount defines model for WorkspaceMount.
type WorkspaceMount struct {
	// Dir Absolute path on the host
	Dir      string `json:"dir"`
	ReadOnly *bool  `json:"read_only,omitempty"`
}

// ImageName defines model for ImageName.
type ImageName = string

// SandboxName defines model for SandboxName.
type SandboxName = string

// PullImageParams defines parameters for PullImage.
type PullImageParams struct {
	// FromImage Image name to pull (e.g. "docker/sandbox-templates")
	FromImage string `form:"fromImage" json:"fromImage"`

	// Tag Tag to pull (e.g. "claude-code")
	Tag *string `form:"tag,omitempty" json:"tag,omitempty"`

	// XRegistryAuth Optional base64url-encoded JSON of registry credentials
	// (same shape Moby uses for its image-pull endpoint). When
	// omitted, the daemon pulls anonymously — sufficient for
	// public images. Env-var-sourced credentials cannot be
	// discovered daemon-side, so clients that resolve creds
	// locally must forward them via this header.
	XRegistryAuth *string `json:"X-Registry-Auth,omitempty"`
}

// ExportImageParams defines parameters for ExportImage.
type ExportImageParams struct {
	// Name Image reference (name, name:tag, or ID). Passed as a query parameter rather than a path segment because image references commonly contain slashes (e.g. "docker/sandbox-templates:claude-code") which do not round-trip cleanly through HTTP path routing.
	Name ImageName `form:"name" json:"name"`
}

// InspectImageParams defines parameters for InspectImage.
type InspectImageParams struct {
	// Name Image reference (name, name:tag, or ID). Passed as a query parameter rather than a path segment because image references commonly contain slashes (e.g. "docker/sandbox-templates:claude-code") which do not round-trip cleanly through HTTP path routing.
	Name ImageName `form:"name" json:"name"`
}

// RemoveImageParams defines parameters for RemoveImage.
type RemoveImageParams struct {
	// Name Image reference (name, name:tag, or ID). Passed as a query parameter rather than a path segment because image references commonly contain slashes (e.g. "docker/sandbox-templates:claude-code") which do not round-trip cleanly through HTTP path routing.
	Name ImageName `form:"name" json:"name"`
}

// ListNetworkPolicyRulesParams defines parameters for ListNetworkPolicyRules.
type ListNetworkPolicyRulesParams struct {
	// Sandbox Filter to rules scoped to this sandbox (plus global rules)
	Sandbox *string `form:"sandbox,omitempty" json:"sandbox,omitempty"`
}

// ResizeExecParams defines parameters for ResizeExec.
type ResizeExecParams struct {
	// H Terminal height in rows
	H int `form:"h" json:"h"`

	// W Terminal width in columns
	W int `form:"w" json:"w"`
}

// GetFileParams defines parameters for GetFile.
type GetFileParams struct {
	// Path Absolute path inside the sandbox
	Path string `form:"path" json:"path"`
}

// PutFileParams defines parameters for PutFile.
type PutFileParams struct {
	// Path Absolute path inside the sandbox to extract into
	Path string `form:"path" json:"path"`
}

// PublishPortsJSONBody defines parameters for PublishPorts.
type PublishPortsJSONBody = []PortPublishRequest

// UnpublishPortsJSONBody defines parameters for UnpublishPorts.
type UnpublishPortsJSONBody = []PortKey

// SetDaemonLogLevelJSONRequestBody defines body for SetDaemonLogLevel for application/json ContentType.
type SetDaemonLogLevelJSONRequestBody = LogLevelRequest

// ModifyNetworkPolicyRulesJSONRequestBody defines body for ModifyNetworkPolicyRules for application/json ContentType.
type ModifyNetworkPolicyRulesJSONRequestBody = PolicyRulesRequest

// ApplyNetworkPolicySetupJSONRequestBody defines body for ApplyNetworkPolicySetup for application/json ContentType.
type ApplyNetworkPolicySetupJSONRequestBody = PolicySetupRequest

// CreateSandboxJSONRequestBody defines body for CreateSandbox for application/json ContentType.
type CreateSandboxJSONRequestBody = SandboxCreateRequest

// SyncCredentialsJSONRequestBody defines body for SyncCredentials for application/json ContentType.
type SyncCredentialsJSONRequestBody = SyncCredentialsRequest

// ExecJSONRequestBody defines body for Exec for application/json ContentType.
type ExecJSONRequestBody = ExecRequest

// AttachExecJSONRequestBody defines body for AttachExec for application/json ContentType.
type AttachExecJSONRequestBody = ExecRequest

// AddKitJSONRequestBody defines body for AddKit for application/json ContentType.
type AddKitJSONRequestBody = AddKitRequest

// PublishPortsJSONRequestBody defines body for PublishPorts for application/json ContentType.
type PublishPortsJSONRequestBody = PublishPortsJSONBody

// ReplaceDesiredPortJSONRequestBody defines body for ReplaceDesiredPort for application/json ContentType.
type ReplaceDesiredPortJSONRequestBody = PortReplaceDesiredRequest

// UnpublishPortsJSONRequestBody defines body for UnpublishPorts for application/json ContentType.
type UnpublishPortsJSONRequestBody = UnpublishPortsJSONBody

// SaveSandboxJSONRequestBody defines body for SaveSandbox for application/json ContentType.
type SaveSandboxJSONRequestBody = SaveRequest

// LegacyVersionCheckJSONRequestBody defines body for LegacyVersionCheck for application/json ContentType.
type LegacyVersionCheckJSONRequestBody = VersionCheckRequest

// AsPolicyRuleActionAllow returns the union data inside the PolicyRuleAction as a PolicyRuleActionAllow
func (t PolicyRuleAction) AsPolicyRuleActionAllow() (PolicyRuleActionAllow, error) {
	var body PolicyRuleActionAllow
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPolicyRuleActionAllow overwrites any union data inside the PolicyRuleAction as the provided PolicyRuleActionAllow
func (t *PolicyRuleAction) FromPolicyRuleActionAllow(v PolicyRuleActionAllow) error {
	v.Action = "allow"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergePolicyRuleActionAllow performs a merge with any union data inside the PolicyRuleAction, using the provided PolicyRuleActionAllow
func (t *PolicyRuleAction) MergePolicyRuleActionAllow(v PolicyRuleActionAllow) error {
	v.Action = "allow"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsPolicyRuleActionDeny returns the union data inside the PolicyRuleAction as a PolicyRuleActionDeny
func (t PolicyRuleAction) AsPolicyRuleActionDeny() (PolicyRuleActionDeny, error) {
	var body PolicyRuleActionDeny
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPolicyRuleActionDeny overwrites any union data inside the PolicyRuleAction as the provided PolicyRuleActionDeny
func (t *PolicyRuleAction) FromPolicyRuleActionDeny(v PolicyRuleActionDeny) error {
	v.Action = "deny"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergePolicyRuleActionDeny performs a merge with any union data inside the PolicyRuleAction, using the provided PolicyRuleActionDeny
func (t *PolicyRuleAction) MergePolicyRuleActionDeny(v PolicyRuleActionDeny) error {
	v.Action = "deny"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsPolicyRuleActionRemoveResource returns the union data inside the PolicyRuleAction as a PolicyRuleActionRemoveResource
func (t PolicyRuleAction) AsPolicyRuleActionRemoveResource() (PolicyRuleActionRemoveResource, error) {
	var body PolicyRuleActionRemoveResource
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPolicyRuleActionRemoveResource overwrites any union data inside the PolicyRuleAction as the provided PolicyRuleActionRemoveResource
func (t *PolicyRuleAction) FromPolicyRuleActionRemoveResource(v PolicyRuleActionRemoveResource) error {
	v.Action = "remove-resource"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergePolicyRuleActionRemoveResource performs a merge with any union data inside the PolicyRuleAction, using the provided PolicyRuleActionRemoveResource
func (t *PolicyRuleAction) MergePolicyRuleActionRemoveResource(v PolicyRuleActionRemoveResource) error {
	v.Action = "remove-resource"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsPolicyRuleActionRemoveID returns the union data inside the PolicyRuleAction as a PolicyRuleActionRemoveID
func (t PolicyRuleAction) AsPolicyRuleActionRemoveID() (PolicyRuleActionRemoveID, error) {
	var body PolicyRuleActionRemoveID
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPolicyRuleActionRemoveID overwrites any union data inside the PolicyRuleAction as the provided PolicyRuleActionRemoveID
func (t *PolicyRuleAction) FromPolicyRuleActionRemoveID(v PolicyRuleActionRemoveID) error {
	v.Action = "remove-id"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergePolicyRuleActionRemoveID performs a merge with any union data inside the PolicyRuleAction, using the provided PolicyRuleActionRemoveID
func (t *PolicyRuleAction) MergePolicyRuleActionRemoveID(v PolicyRuleActionRemoveID) error {
	v.Action = "remove-id"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t PolicyRuleAction) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"action"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t PolicyRuleAction) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "allow":
		return t.AsPolicyRuleActionAllow()
	case "deny":
		return t.AsPolicyRuleActionDeny()
	case "remove-id":
		return t.AsPolicyRuleActionRemoveID()
	case "remove-resource":
		return t.AsPolicyRuleActionRemoveResource()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t PolicyRuleAction) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *PolicyRuleAction) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
